# Generated by Django 5.0.2 on 2024-02-21 18:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_alter_petmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('procedure', models.TextField()),
                ('imageUrl', models.URLField()),
                ('dateOfAttention', models.DateTimeField(default=datetime.datetime.now)),
                ('is_delete', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petmodel')),
            ],
            options={
                'db_table': 'attentions',
            },
        ),
    ]
