# Generated by Django 5.0.2 on 2024-02-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(default='mixta', max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('fotoUrl', models.URLField(default='https://www.shutterstock.com/image-vector/animal-paw-print-vector-icon-260nw-1820447291.jpg')),
                ('esterilizado', models.BooleanField(default=False)),
                ('Peso', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
            options={
                'db_table': 'pets',
            },
        ),
    ]
