# Generated by Django 5.0.2 on 2024-02-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petmodel',
            old_name='Peso',
            new_name='peso',
        ),
        migrations.AddField(
            model_name='petmodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
