# Generated by Django 5.0.2 on 2024-02-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoiments', '0002_alter_appoimentmodel_veterinarian'),
        ('pets', '0002_alter_petmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoimentmodel',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appoiments', to='pets.petmodel'),
        ),
    ]
